[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.17"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}" 
optimism = "${OPTIMISM_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
optimismGoerli = "${OPTIMISM_GOERLI_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
optimism = { key = "${ETHERSCAN_KEY}" }
goerli = { key = "${ETHERSCAN_KEY}" }
optimismGoerli = { key = "${ETHERSCAN_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config